### ISSUE TITLE
データベースに保存するタイトルをメール件名から任意の値にするフック

### ISSUE THREAD

**Issue by naoshiro** [inc2734/mw-wp-form#100]
よろしくお願いします。
データベースに保存するタイトルをメール件名から任意の値にしたいのですがよい方法がみつからず。(理由としては件名に個人情報が含まれるケースがあるため)
もしよろしければ検討いただけると助かります。

https://github.com/inc2734/mw-wp-form/blob/master/classes/services/class.mail-parser.php#L92
※上記部分にフィルターフックを追加することで可能かと思いました。

よろしくお願いします。

**Comment by inc2734** [comment]
下記のフックでできないでしょうか？
https://plugins.2inc.org/mw-wp-form/filter-hook/mwform_admin_mail/

**Comment by naoshiro** [comment]
@inc2734 
なるほど！DB保存前に `mwform_admin_mail_raw_mw-wp-form-xxx` で変更し、
`mwform_admin_mail_mw-wp-form-xxx` で件名を戻せばDB保存分だけ変更できますね。
ありがとうございます！助かりました！
