### ISSUE TITLE
「%20」を含むURLリダイレクトを繰り返します

### ISSUE THREAD

**Issue by SergeiLF** [inc2734/mw-wp-form#124]
プラグインを使用していて不具合がありましたのでご連絡いたします。

「%20」を含むURLならプラグインを使うページのリダイレクトを繰り返してしまします。
https://www.family-chair.co.jp/lineup/shoulderpro/?utm_medium=ppc_%E3%82%B4%E3%83%AB%E3%83%95%E3%82%B9%E3%82%AF%E3%83%BC%E3%83%AB&utm_source=google&utm_term=%E3%82%B4%E3%83%AB%E3%83%95%20%E3%82%B9%E3%82%AF%E3%83%BC%E3%83%AB%20%E6%A8%AA%E6%B5%9C%E5%B8%82

URLとしては問題ありませんが、URLに使われている文字（おそらく「%20」）が原因でこちらの関数内でマッチしていないようです。
https://github.com/inc2734/mw-wp-form/blob/48e03dd38bfed15aab51e1263c5d5b42674879a3/classes/services/class.redirected.php#L219

例えば、
こちらのURLはリダイレクトを繰り返しませんが、
https://www.family-chair.co.jp/lineup/shoulderpro/?utm_medium=ppc_%E3%82%B4%E3%83%AB%E3%83%95%E3%82%B9%E3%82%AF%E3%83%BC%E3%83%AB&utm_source=google

こちらのURLはリダイレクトを繰り返します。
https://www.family-chair.co.jp/lineup/shoulderpro/?utm_medium=ppc_%E3%82%B4%E3%83%AB%E3%83%95%E3%82%B9%E3%82%AF%E3%83%BC%E3%83%AB&utm_source=google%20

期待する解決：
「%20」を含むURLのページでリダイレクトしないようにしていただきたいです。

**Comment by inc2734** [comment]
フォームの編集画面で URL の設定をしていますか？ もししているのであれば空にするとどうなりますか？

**Comment by SergeiLF** [comment]
@inc2734 ありがとうございます。編集画面のURL設定を空にすると、リロード ループは無くなります。ただ、URL設定を空にするとフォームが正常に遷移しなくなります

**Comment by inc2734** [comment]
「正常に遷移しなくなる」というのは具体的にどのような挙動になりますか？

**Comment by SergeiLF** [comment]
URL設定の「入力画面URL」を空にすると、mwform_bbackのボタンで戻った際にフォームが表示されず下記画面になってしまいます。
![image](https://user-images.githubusercontent.com/59723515/129839347-cbf58073-6435-43d8-a3ee-be3262c73ee8.png)

**Comment by inc2734** [comment]
あ、「入力画面URL」だけを空にするのではなくて、確認画面 URL も完了画面 URL もすべて空にするとどうなりますか？ すべて空にしても「このページには直接アクセスできません。」になりますか？

**Comment by SergeiLF** [comment]
ありがとうございます！
URL設定をすべて空にしても動作は問題ないですが、送信後の完了画面（サンクスページ）が同一ページになってしまいます。
※サンクスページ は別ページにしたい
