### ISSUE TITLE
dosen't support "MW_WP_Form_Abstract_Validation_Rule::getName()" already. This will be removed in the next version.が出力される

### ISSUE THREAD

**Issue by toshi808** [inc2734/mw-wp-form#145]
以下のメッセージがPHPデバッグメッセージに出力されます。
validation-rules/class.zip.php
validation-rules/class.tel.php
で発生しているようです。
よろしくお願いします。

環境: MW WP Form 4.4.5, WordPress 6.3, Apache

PHP debug message
MW WP Form dosen't support "MW_WP_Form_Abstract_Validation_Rule::getName()" already. This will be removed in the next version. You should use "MW_WP_Form_Abstract_Validation_Rule::get_name()". /var/www/html/wp-content/plugins/mw-wp-form/classes/validation-rules/class.tel.php line 77

MW WP Form dosen't support "MW_WP_Form_Abstract_Validation_Rule::getName()" already. This will be removed in the next version. You should use "MW_WP_Form_Abstract_Validation_Rule::get_name()". /var/www/html/wp-content/plugins/mw-wp-form/classes/validation-rules/class.tel.php line 77MW WP Form dosen't support "MW_WP_Form_Abstract_Validation_Rule::getName()" already. This will be removed in the next version. You should use "MW_WP_Form_Abstract_Validation_Rule::get_name()". /var/www/html/wp-content/plugins/mw-wp-form/classes/validation-rules/class.zip.php line 72

**Comment by inc2734** [comment]
issue 気づいていませんでした、遅くなってすみません。ご報告ありがとうございます！
