### ISSUE TITLE
ページキャッシュが効いている場合でも動作するようにしたい

### ISSUE THREAD

**Issue by natsumesou** [inc2734/mw-wp-form#146]
WordPressのホスティングサービスでページキャッシュが強制されているような場合、本プラグインが正常に動作しないためページキャッシュが効くようなケースでもサポートすることで、カバーできるプラットフォームが増える上に、プラグイン含めより高速な動作が期待できます。

## ページキャッシュが効いていると動作しない原因

ショートコードにコアな処理が乗っているため、ページキャッシュで処理される場合ショートコード内の処理が実行されない。
そのため
https://github.com/inc2734/mw-wp-form/blob/6ea4449b5fc0e33dec360f16bab0f281b0e68816/classes/services/class.exec-shortcode.php#L74
にある `clear_values` が呼ばれないせいでセッションがクリアされず、状態がおかしくなる。
現状上記処理の内容しか把握していませんが、他の処理でも同様に引っかかる可能性はあります。

## 対策案

1. ショートコードに表示以外のコアな処理を乗せない
2. ショートコードをajax経由で呼び出すことでページキャッシュに乗らないようにする

あたりかと思いますが、2が一般的な対応かと思います。
影響範囲がどの程度ある変更か把握していないため、プラグインの根本的な処理を見直す必要があるなど非現実的な提案の可能性もあります。そのためissue自体の方向性含めてのご提案になります、よろしくお願いします。

**Comment by inc2734** [comment]
残念ですが MW WP Form の仕組み上難しいと思います。無理に変えると後方互換性を完全に崩してしまうことになる可能性が非常に高いと思います。
