### ISSUE TITLE
アドオン開発について

### ISSUE THREAD

**Issue by tomothumb** [inc2734/mw-wp-form#26]
こんにちは、アドオンがあることを知ったのですが、アドオン提供についてかかれたドキュメントはございますか？

具体的にいいますと、ajaxzipのライブラリをつかえるような拡張を実装できないかと考えています。
ajaxzipって日本特有なのでmw wp formの本体には取り込むべきではないと思いますし、アドオン形式で作成できればよいなーと考えました。

あわせて、アドオンは有償販売されていらっしゃるようなので、OSSとして開発、もしくは、第三者がアドオンを作成し、それを有償販売してよいものなのかどうかも気になりました。

いかがお考えでしょうか？

**Comment by inc2734** [comment]
公式サイトにフィルターフックの説明を載せていますので、それにフックさせてアドオンの機能を追加していく形になります。ただ、たぶんマニュアルの更新も漏れがあったりする可能性があるので、MW WP Form のコード自体を直接見られたほうが良いかもしれません…。アドオン自体の作成等についてのドキュメントはありません。

> あわせて、アドオンは有償販売されていらっしゃるようなので、OSSとして開発、もしくは、第三者がアドオンを作成し、それを有償販売してよいものなのかどうかも気になりました。

有償で販売すること自体は全く問題ありません。ただ、MW WP Form が GPL なので、作成するアドオンも GPL にする必要があります。

**Comment by tomothumb** [comment]
ありがとうございます！参考にさせていただきます。
