### ISSUE TITLE
送信時のアクションフック

### ISSUE THREAD

**Issue by tomothumb** [inc2734/mw-wp-form#31]
マニュアルやコードを読む限り、フィルターフックはいくつかあるようですが、
アクションフックもいくつかあれば、柔軟性が広がるのかなと思いました。

具体的に言いますと、
送信時にメール以外の何かへ通知するような処理、
特定条件で完了画面のリダイレクト先を変更するなどが可能になるのかなと。

contact form7 でいう、wpcf7_before_send_mailのようなアクションフックです。

いかが思われますか？

**Comment by inc2734** [comment]
仕事などでリダイレクトや送信先の追加・変更等がある場合はフィルターフックを使ってやっていましたが、確かにアクションフックのほうがスマートかもしれませんね。フィルターフックでリダイレクトすると後処理とか面倒なので…。
