### ISSUE TITLE
フィールドのclass付与について

### ISSUE THREAD

**Issue by tomothumb** [inc2734/mw-wp-form#34]
ご存知かもしれませんが、郵便番号から住所を自動登録するスクリプトに、ajaxzip3.jsとyubinbango.jsがございます。両方日本国内用です。
2015年時点で、推奨されてるのはyubinbangoのようです。
https://code.google.com/p/ajaxzip3/

で、ajaxzip3.jsの場合はJSからセレクタ指定して動作させれるんですけど、
yubinbango.jsの場合、該当のフィールドおよびフォームタグにclassを指定して、動作させる仕様です。
mw-wp-formでclassは付与させない仕様にされていらっしゃったと思いますので、このスクリプトを動作させれません。

JSライブラリを柔軟にすべきかもしれませんし、別にmw-wp-formを柔軟にするのが全てだとは思っておりません。
一応現状でこういう事例がありましたよということで報告いたします。

**Comment by inc2734** [comment]
Move to https://github.com/inc2734/mw-wp-form/issues/7
