### ISSUE TITLE
Fileでアップロードされた画像のIDを取得したい。

### ISSUE THREAD

**Issue by tomothumb** [inc2734/mw-wp-form#42]
Issueではなく要望です。

ファイル添付ありのフォーム送信したタイミングで、画像付きの投稿として下書き保存のようなことをしています。

mwform_before_send_admin_mail_mw-xxxxxのフックで、POSTデータがとれるので、
そのアクションフック内で、メディアライブラリに保存し、投稿にメディアのIDを付与するというかたちで一応解決していますが、
この場合、フォームのログとして登録された画像ファイルと、アクションフック内で登録された画像ファイルと、実質、同じ画像が2度保存されてしまいます。
フォームのログとして保存されたファイルのメディアライブラリのIDを活用できないものかと考えています。

フォームのログのIDかあたりを、mwform_before_send_admin_mail_mw-xxxxx、内で取得できさえすれば、解決しそうにおもうのですが、手段はありますか？

この辺りのコードです。($insert_contact_data_id)かな。
https://github.com/inc2734/mw-wp-form/blob/master/classes%2Fservices%2Fclass.mail-parser.php#L64

**Comment by inc2734** [comment]
https://github.com/inc2734/mw-wp-form/commit/6572290571aed9c0b0d2ad5d9340ba5bbb8b439d
