### ISSUE TITLE
完了画面のURLが設定されていると、バリデーションの結果に関わらずリダイレクトされてしまう

### ISSUE THREAD

**Issue by sinack** [inc2734/mw-wp-form#74]
管理画面で完了画面用のURLが設定されていると、バリデーションで必須項目を設定していても送信ボタンを押下すると、フォームのページが読み込まれたあと、設定されていた完了画面のページに遷移します。

バリデーションエラーメッセージなども表示されず、メールは送信されません。
完了画面のURLが設定されていなければ、メールも送信され、バリデーションも正常に動作しているようでした。

**Comment by inc2734** [comment]
お！まじですか！ご報告ありがとうございます。
手元で同じ環境を再現したいと思いますので、下記の情報を教えていただけますでしょうか？

- MW WP Form のバージョン
- 入力・確認・完了画面の URL 設定（ドメイン部分は伏せ字で構いません）
- 設定しているバリデーションルール

**Comment by inc2734** [comment]
4.0！検証ありがとうございます！！！！
もう4.0着手したときから1年になるのでいい加減リリースしないとですね…。
報告助かります、時間見つけて検証＆修正します。
