### ISSUE TITLE
【v4】入力→確認→送信 だとメールでの改行がなくなる

### ISSUE THREAD

**Issue by inc2734** [inc2734/mw-wp-form#75]
> mw-wp-form 4 をためしに使っていて気づいた点があったのでご連絡です。
> textareaを使ったときに 入力→送信 だと問題ないのですが。
> 入力→確認→送信 だとメールでの改行がなくなるようです。ver3では問題なしでした。
> 
> 調べてたら、確認画面でのhiddenのときに改行が消えているようです。
> 
> Model の MW_WP_Form_Form　で 
> function hidden( $name, $value ) {
>     return self::remove_linefeed_space( ～ );
> }
> が、ver4で remove_newline_space() に変えられたようなので、ここらへんかなと思いました。
> ただ、ここらへんでコード読むのを止めたので、正確にはわからず。すんません。

**Comment by K-at-PeS** [comment]
現在使用している下記環境で、確認画面に遷移する設定を利用すると、同様の事象が発生いたします。
MW WP Form ver. 4.4.0
Wordpress 5.6
PHP 7.4.13
