### ISSUE TITLE
数値 0 を登録したとき、問い合わせデータ表示とCSVダウンロードの値がカラになる？

### ISSUE THREAD

**Issue by haruit** [inc2734/mw-wp-form#76]
次のようなフォームで、

```
 [mwform_number name="element-10" step="0.1" class="spinner"]
```
 
このカラムに 0 を登録すると、問い合わせデータの表示がカラ、
CSVダウンロードした値もカラになります。

以下のソースように変更することで 0 が有効になったのですが、この変更方法は正しいでしょうか。
使い方に問題がありそうでしょうか？

表示部分:

```
// mw-wp-form/classes/controllers/class.contact-data-list.php (166行目)

} elseif ( $post_meta ) {
      $value = esc_html( $post_meta );
```

この部分を次のように変更.

```
} elseif ( $post_meta || $post_meta == 0) { 
```

CSVダウンロード部分:

```
// mw-wp-form/classes/models/class.csv.php (184行目)

$column = ( $post_meta ) ? $post_meta : ''; 
```

この部分を次のように変更.

```
$column = ( $post_meta || $post_meta == 0) ? $post_meta : ''; 
```

**Comment by inc2734** [comment]
お知らせ＆提案ありがとうございます！！確かにいまの実装だと 0 でませんね…。
`( $post_meta || $post_meta == 0)` だと `false` や `null` のときも通っちゃうなと思ったのですが、`false` や `null` は結局画面には表示されないので、いっそなんでも表示するようにしちゃっても良いのかなと思いました（未検証）。

時間あるときにやってみます。
