### ISSUE TITLE
問い合わせ件数項目でゴミ箱に移したデータが表示されません。

### ISSUE THREAD

**Issue by hisanuco** [inc2734/mw-wp-form#77]
ゴミ箱のタブには件数が表示されているのに、ゴミ箱内を示す表には「ゴミ箱にデータはありません」と表示され完全な削除が出来ないでいます。

**Comment by inc2734** [comment]
<img width="1117" alt="2018-09-08 14 32 03" src="https://user-images.githubusercontent.com/1094306/45250707-fbaf9800-b373-11e8-82ff-d654de361885.png">

こうならないということですよねこうならないということですよね？
ログインしているユーザーは管理者でしょうか？また、いまログインしているユーザーで作成したフォームをすぐに削除してゴミ箱ページに移動した場合も、消したフォームは表示されませんか？

**Comment by hisanuco** [comment]
管理者ですね。フォームの方はそのようにゴミ箱内が閲覧出来ました。
言葉が足りてなかったので済みませんでした。
問い合わせデータの項目でした。
問い合わせデータ > 件数以降のページでゴミ箱内の表示が出来ないでいます。

<img width="836" alt="mw-cap20180908" src="https://user-images.githubusercontent.com/6804847/45252485-198bf580-b392-11e8-8413-d189a3f35131.png">

**Comment by hisanuco** [comment]
https://github.com/inc2734/mw-wp-form/issues/77#issuecomment-419614232 の内容もゴミ箱に入れた直後で以下のようになっていました。

postsテーブルは以下
<img width="426" alt="posts-cap20180908" src="https://user-images.githubusercontent.com/6804847/45252538-e9912200-b392-11e8-81a5-1815fbf65d52.png">
となっており
postsmetaテーブルは
<img width="626" alt="postmeta-cap20180908" src="https://user-images.githubusercontent.com/6804847/45252547-062d5a00-b393-11e8-95d7-21a075930621.png">
となっていて、ゴミ箱内のステータス更新はされないものなのでしょうか？

**Comment by inc2734** [comment]
あ、問い合わせデータのところですね、失礼しました。
DB 云々については MW WP Form で update 等発行していないのでなぜそうなるのかはわかりませんが、数字がずれるのがどこの処理のせいなのかはわかりました。

https://github.com/inc2734/mw-wp-form/blob/master/classes/controllers/class.contact-data-list.php#L60-L78

このメソッドですね。フックで表示条件を指定できるように用意したメソッド（だと思う）ですが、フックしてなくてもなんらか制限がかかっちゃうようです。

**Comment by inc2734** [comment]
https://github.com/inc2734/mw-wp-form/pull/79

このプルリクでどうですかね？

**Comment by hisanuco** [comment]
テストした結果、表示されましたし削除も出来ました。
ありがとうございます。
