### ISSUE TITLE
テンプレート内の任意の場所にバリデーションエラー表示したい

### ISSUE THREAD

**Issue by fuyuan9** [inc2734/mw-wp-form#90]
こんにちわ
mw-wp-form使わせて頂いてます。
ありがとうございます。

mw-wp-formにBootstrapなどのCSSフレームワークを適用したいです。
CSSフレームワークでは、多く場合HTMLの構造が決められており
現在、バリデーションエラー表示のHTML構造を変更する仕組みがないため
フレームワークに合わせたHTML構造にできません。

テンプレート内にバリデーションエラー文言を
変数で渡すオプションがあれば良いと考えています。
いかがでしょうか？
ご意見を聞きたいです。
よろしくお願いします。

**Comment by inc2734** [comment]
https://github.com/inc2734/mw-wp-form/blob/master/classes/abstract/class.form-field.php#L157-L165

このフックでカスタマイズできると思います。

**Comment by fuyuan9** [comment]
@inc2734 ありがとうございます。フック調べてみます 👀
