### ISSUE TITLE
お問い合わせデータの対応状況を変更するとNoticeが発生する

### ISSUE THREAD

**Issue by naoshiro** [inc2734/mw-wp-form#95]
お問い合わせデータの対応状況変更するとnoticeが発生しましたのでご報告です。

## 現象

![image](https://user-images.githubusercontent.com/2981216/62033308-a2b84f00-b226-11e9-8d90-6a06772bbbd5.png)

1. お問い合わせデータの対応状況を`未対応`から`保留`変更し保存した際に発生
2. WP_DEBUGはtrue

## 原因と思われる記述

https://github.com/inc2734/mw-wp-form/blob/e5b9cd3c74883c5c0f07d106efc01b40178b8176/classes/controllers/class.contact-data.php#L34

保存処理時にはGET値がないため？

**Comment by inc2734** [comment]
ご報告ありがとうございます！
